### PR TITLE
Added Deployment support to helm

### LINKED ISSUE #456: Deployment k8s objects cannot be installed with helm
When trying to install a _Deployment_ k8s object I get the following error:

```
➜  helm install nginx
---> Running `kubectl create -f` ...
error validating "STDIN": error validating data: API version "" isn't supported, only supports API versions ["extensions/v1beta1" "componentconfig/v1alpha1" "batch/v1" "autoscaling/v1" "authorization.k8s.io/v1beta1" "v1" "metrics/v1alpha1"]; if you choose to ignore these errors, turn validation off with --validate=false
```

The deployment object is taken from the helm test sample:

```
➜ cat ~/.helm/workspace/charts/nginx/manifests/example-pod.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

The dry-run shows that the object is not read properly from file:

```
➜  helm install nginx --dry-run
---> Running `kubectl create -f` ...
[CMD] kubectl create -f - < {}
---> Done
========================================
# nginx

Describe your chart here. Link to upstream repositories, Docker images or any
external documentation.

If your application requires any specific configuration like Secrets, you may
include that information here.
========================================
```

helm compiled from `c983f0a` commit.

### PR DESCRIPTION
**Pull request by spiddy**
Fixes #456

### CODE REVIEW

**Comment by krancour** [comment]
Initially, LGTM.  I want to take a look at what tests, if any, should be added to go along with this before I tag it as such.

**Comment by krancour** [comment]
@spiddy could you please, add a test deployment manifest to `testdata/charts/kitchensink/manifests`?  Probably updates to `chart_test.go` are called for as well.

Also, please update the commit message to "fix(helm): Add support for deployment resources"

Thanks in advance for the effort on this!

**Comment by spiddy** [comment]
Done, Added tests and renamed commit.

**Comment by bacongobbler** [comment]
thanks @spiddy!

**Pull request merged**
