### PR TITLE
fix(install): let VersionedObject marshal its own JSON

### LINKED ISSUE #477: helmc fails with apiVersion v1 and kind LimitRange
Prior to this command the namespace was already created.

```
 helmc install system                                                                                                                                                                     
---> Running `kubectl create -f` ...
error validating "STDIN": error validating data: API version "" isn't supported, only supports API versions ["componentconfig/v1alpha1" "extensions/v1beta1" "metrics/v1alpha1" "v1" "authorization.k8s.io/v1beta1" "autoscaling/v1" "batch/v1"]; if you choose to ignore these errors, turn validation off with --validate=false

[ERROR] Failed to upload manifests: exit status 1
```

kubectl works
```
kubectl create -f system-limits.yaml                                                                                                                                                      
limitrange "system-limits" created
```

Example:
```
apiVersion: v1
kind: LimitRange
metadata:
  name: system-limits
  namespace: system
spec:
  limits:
  - default:
      memory: 1000Mi
    defaultRequest:
      cpu: 250m
      memory: 500Mi
    type: Container
```

### PR DESCRIPTION
**Pull request by mboersma**
The marshalAndCreate method was always returning empty JSON for unknown manifest types.

Fixes #477.

### CODE REVIEW

**Comment by mboersma** [comment]
@sstarcher I think this fixes the issue with `helmc install` of your chart with a `LimitRange`. If you're able to build this version locally and try it, please let me know.

**Comment by sstarcher** [comment]
I hang forever at ```[INFO] Fetching updates for speter.net/go/exp/math/dec/inf.```
when running make bootstrap gogo godeps

**Comment by mboersma** [comment]
> I hang forever at `[INFO] Fetching updates for speter.net/go/exp/math/dec/inf.`

Ugh--we have all felt that pain. #476 should have fixed that up, though... I just did `rm -rf vendor/ && make bootstrap native-build install` and it took a long time but did finish without errors. Is the branch where you are testing this up-to-date with helm-classic master?

**Comment by mboersma** [comment]
A prebuilt version of `helmc` with this fix is available at  [ Download ](https://bintray.com/deis/helm-ci/helmc/_latestVersion#files).

**Comment by sstarcher** [comment]
@mboersma I verified that fixes my problem

**Pull request merged**
