### PR TITLE
ref(helmc): Rename the uploaded binary files to start with helmc

### PR DESCRIPTION
**Pull request by kmala**
ref #450 

cc @krancour

### CODE REVIEW

**Comment by krancour** [comment]
Do we know how this script gets out to https://get.helm.sh?

**Comment by krancour** [comment]
Per @sgoings this is not the actual source of the install script found at https://get.helm.io.

Should we consider a new PR that removes the script from here to avoid this same confusion in the future?

**Comment by sgoings** [comment]
I'd be a fan of removing the install script from this repository or getting auto deployment logic from the internal repo into this one. 😄

**Comment by krancour** [comment]
I'm going to close this in favor of a forthcoming PR that removes the script.

**Comment by kmala** [comment]
This PR also has a small fix which i think is needed to name the binary zip file to helmc unless we don't wanna do it?

**Comment by krancour** [comment]
We should.  Maybe reopen or resubmit with just that one change?

**Comment by kmala** [comment]
@krancour kept just that one change and renamed the PR

**Pull request merged**
